# Use NVIDIA's base image for CUDA
FROM nvidia/cuda:12.6.3-devel-ubuntu24.04

# Install dependencies
RUN apt-get update && apt-get install -y \
    clang \
    libomp-dev \
    clang-tools \
    && rm -rf /var/lib/apt/lists/*

# Adds openmp target offloading shared object files to path
ENV LD_LIBRARY_PATH=/usr/lib/llvm-18/lib:$LD_LIBRARY_PATH

# Set the working directory
WORKDIR /home/src/openmp

# Provide default command
CMD ["clang", "--help"]
